### ISSUE TITLE
Environment variables naming scheme

### ISSUE THREAD

**Issue by janekolszak** [ory-am/hydra#136]
Hi,
We can pass some data to hydra via environment variables - awesome and very useful for docker-compose deployment.

Shouldn't the env variables have a common prefix "HYDRA_"  to avoid collisions?

**Comment by arekkas** [comment]
Good point, that really depends on the environment. In a docker environment, there should be close to zero collisions, because you set env vars per container. Some of the env vars like `PORT` and `HOST` are actually best practice because they make hydra run on heroku/cloud foundry/flynn/dokku/... out of the box.

However, stuff like tls paths could be scoped - did name collision happen in your environment?

**Comment by janekolszak** [comment]
Well if your container has only Hydra inside then you're right.

**Comment by arekkas** [comment]
You can also set env vars with `ENV=foo hydra` - so i think we should be good :)
