### ISSUE TITLE
include a migration routine for databases

### ISSUE THREAD

**Issue by arekkas** [ory-am/hydra#194]

**Comment by janekolszak** [comment]
I think all database code should be in a separate folder, in separate sql scripts. All tables in one place.
First script would be `001-create-db.sql`. When there's an update we add a script `002-some-update.sql`
In order to create the database hydra would:
- create transaction
- run scripts in order
- commit

In order to update the database schema hydra would:
- create transaction
- run scripts from the updated version to the latest
- commit

If hydra does this automatically we get rid of the problematic (for user) schema updates.

**Comment by arekkas** [comment]
a list of sql migration tools:

* https://github.com/DavidHuie/gomigrate
* https://github.com/rubenv/sql-migrate
* https://github.com/mattes/migrate

**Comment by 20zinnm** [comment]
I highly recommend migrate--you can see a great usage of it [here](https://github.com/drone/drone/tree/master/store).

**Comment by arekkas** [comment]
awesome, thanks!

**Comment by arekkas** [comment]
see https://github.com/ory-am/hydra/pull/329/commits/070520d3d862e39ce1a199be7f50f95380ad7e1e
