### ISSUE TITLE
Request for Comment: Fair Source License / Business Source License

### ISSUE THREAD

**Issue by arekkas** [ory-am/hydra#227]
Currently, Hydra is available under Apache 2.0 license. As traction keeps growing and more and more people want to use Hydra, doing that hinders development on other projects.

We have been thinking about how to generate revenue from our open source projects to ensure their advancement and continuous improvement. But building a business on a 20% margin on top of support is challenging and not scalable. This is why we are continuously looking for business models that allow us to do open source but pay our employees industry-level wages.

Some of you might have heard of the licensing model that MariaDB is going to use, if not read here: https://techcrunch.com/2016/08/19/mysql-founder-tries-a-new-software-licensing-model/

Our advisors are favorable of that approach. It would enable us to charge licensing fees for large (*to be defined*) deployments but ensure that Hydra will eventually be available as Apache 2.0.

Contrary to SaaS solutions, users of Hydra will always be able to operate and modify Hydra, even when our business closes. This is a huge advantage and why we chose the Open Source path.

On the downside, the proposed licensing model might be intransparent (e.g.: How much CPU/memory does hydra require in real life?) or averse potential adopters.

Before making any rash decisions I would like to gather your feedback on this issue. We will consider silence as an indicator that you trust our decision regardless of the outcome. So, please speak out if you want to contribute to this discussion.

Licenses we are currently considering:
* Business Source License
  * http://monty-says.blogspot.de/2013/06/business-source-software-license-with.html
  * https://mariadb.com/bsl-faq-mariadb
  * https://mariadb.com/bsl-faq-adopting
* Fair Source License: https://fair.io

**Comment by waynerobinson** [comment]
Basing licensing on system resources is fine a for something like a DB because usage of it is basically defined by resource use. But for an authentication engine, that doesn't really sound like it fits.

We really like the idea of this being open source and, as mentioned privately, would be happy to pay for support of this as well as ad-hoc consulting work to improve the system itself.

Other open source products (https://github.com/mperham/sidekiq for example) will have a freemium-like model based on features. Mike has Pro and Enterprise levels for his product, but keeps everything else open source. He also provides absolutely no support for the open-source version and that model works for him.

If you wanted to go Freemium, something like the Warden policy-based features could be an interesting upsell as they're mostly separate from the core authentication layer.

If you wanted to use a resource-based model, may I suggest something like active user count (e.g. https://auth0.com/pricing). This seems to fit better with the core product.

**Comment by arekkas** [comment]
Thank you for your thoughts and links! I am very confident that Hydra will stay with the Apache 2.0 license. :)

**Comment by arekkas** [comment]
Closed for now
