### ISSUE TITLE
SCIM 2.0

### ISSUE THREAD

**Issue by drasko** [ory-am/hydra#235]
@arekkas I was wondering if you looked into this: http://www.simplecloud.info/, and what is your opinion on supporting SCIM 2.0 standard in Hydra?

**Comment by arekkas** [comment]
I don't think tgat hydra is going to support identity management any time soon. Maybe a different product but there are no plans yet.

Gesendet mit meinem HTC

----- Reply message -----
Von: "Drasko DRASKOVIC" <notifications@github.com>
An: "ory-am/hydra" <hydra@noreply.github.com>
Cc: "Aeneas" <aeneas@serlo.org>, "Mention" <mention@noreply.github.com>
Betreff: [ory-am/hydra] SCIM 2.0 (#235)
Datum: Fr., Aug. 26, 2016 14:45

@arekkas I was wondering if you looked into this: http://www.simplecloud.info/, and what is your opinion on supporting SCIM 2.0 standard in Hydra?

-- 
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/ory-am/hydra/issues/235
