### ISSUE TITLE
core: document hard-wired JWK sets

### ISSUE THREAD

**Issue by waynerobinson** [ory-am/hydra#247]
How do we manually add keys for challenges, etc so they don't change constantly on restart or have to request them specifically from the endpoint every time we need them?

Or is that the point? That challenge keys for the consent server, etc need to be requested from Hydra every single time they're used?

I see key endpoints, but nowhere to see what keys we're meant to setup and exactly what each is used for.

**Comment by arekkas** [comment]
> How do we manually add keys for challenges, etc so they don't change constantly on restart

Keys only change on new installs or if there is no way to persist them. This usually happens if you use hydra without a database. Once you've setup rethinkdb with hydra, hydra will generate them only once.

> That challenge keys for the consent server, etc need to be requested from Hydra every single time they're used?

In the future, there will be key rotation but you shouldn't be required to lookup the keys always. It is enough to look them up if validation fails.

> I see key endpoints, but nowhere to see what keys we're meant to setup and exactly what each is used for.

Good point, this isn't documented at the moment. Here is a list of keys: #239

Usually, you should not need to modify them, except for the HTTPS TLS key, which can also be set using environment variables or a command line flag.

**Comment by waynerobinson** [comment]
Just to confirm, the intention is to change the keys to all the `hydra.*` prefixed forms?

**Comment by arekkas** [comment]
Yes, this already happened on the 0.5.0 PR
