### ISSUE TITLE
Consider extract Go SDK package into separate repository

### ISSUE THREAD

**Issue by nikolay-turpitko** [ory-am/hydra#266]
SDK package now is a directory in the Hydra project. This is not very convenient to be used with go get, glide get, etc. SDK depends on several other packages within Hydra repository and adds some other transitive dependencies, which are unnecessary to a simple task of sending HTTP request to Hydra server. Effectively, when we use glide for dependency management, we have to add whole Hydra as a dependency of the client app. Please, consider to extract Hydra Go SDK to separate repo.

**Comment by arekkas** [comment]
Thanks for the feedback, unfortunately this is currently not an option as the SDK will always depend on the basic hydra code. This is owed to the fact that hydra comes with HTTP clients for all endpoints which are well integrated in the testing suite. Redoing this in a different code base is prone to errors caused by api changes as well as more work to maintain.

I think that glide is exactly the right tool for this sort of issue, as you do not need to commit the vendor directory any more to get reproducible builds. Additionally, glide install times are, even for larger projects, quite speedy.

Once #249 lands, you might be able to fallback to autogenerated code, but before that I don't see this being done by our organization.

**Comment by nikolay-turpitko** [comment]
Well, OK. #249 is an interesting approach, might be a good alternative.
