### ISSUE TITLE
Fail to execute "create a new client" in apiary docs

### ISSUE THREAD

**Issue by favadi** [ory-am/hydra#64]
I'm learning how to use hydra and trying [the example to create a new client](http://docs.hydra6.apiary.io/#reference/client/client-collection/create-a-new-client?console=1), click send request to prod server, but it responses with 404 error code. 

So:

* is the documents out of date?
* is the production server out of date?

Or I somehow I was doing something wrong?

**Comment by arekkas** [comment]
Hey sorry for the inconvenience, the docs are unfortunately out of date. I'm working on a major refactor right now, so things will change again very soon.
I suggest to wait for #62 to be merged.

Updated docs will follow soon after.

----- Reply message -----
Von: "Diep Pham" <notifications@github.com>
An: "ory-am/hydra" <hydra@noreply.github.com>
Betreff: [ory-am/hydra] Fail to execute "create a new client" in apiary docs (#64)
Datum: Di., Apr. 26, 2016 18:04

I'm learning how to use hydra and trying [the example to create a new client](http://docs.hydra6.apiary.io/#reference/client/client-collection/create-a-new-client?console=1), click send request to prod server, but it responses with 404 error code. 

So:

* is the documents out of date?
* is the production server out of date?

Or I somehow I was doing something wrong?



---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/ory-am/hydra/issues/64

**Comment by ng-vu** [comment]
How about your estimation? How long will #62 be merged?

**Comment by arekkas** [comment]
I would give it a month, at maximum 2 months. It really depends on the workload from other projects we are currently involved in. 

However, I am confident that the wait will be worthwile. There are a some security issues addressed (kicking out osin and replacing it with fosite), a lot will be done performance wise (switching from polling to in memory & pub/sub with rethinkdb) and it will be much easier to integrate with existing identity providers like LDAP, custom codebases and social login like facebook and the sorts. Additionally, I have defined a very clean workflow for login and consent which will be implemented as well.

The code will be much more lightweight and I am looking to partner up with a broadcast driven micro service paas, who might use hydra for authentication. So there will be a lot of real world application and performance inspection.

All these changes above required me to do a full rewrite rather than a refactor, which is why I would not build my project on hydra at this point in time.

**Comment by arekkas** [comment]
I will additionally add two factor authentication, other means of one time passwords, more security measures and so on ;)

**Comment by arekkas** [comment]
it's merged
