### ISSUE TITLE
Document error redirect to identity provider

### ISSUE THREAD

**Issue by janekolszak** [ory-am/hydra#96]
Hi,
I think I found a small bug in consent handling by Hydra when integrating with a IdP.

When I run `hydra token user --skip-tls-verify` I get a URL. 
The first time I visit it's OK and I get:
``` 
Access Token: 8e3ncb7eCmGKkCqfgPG5aG6an2a99PBU8yS0n1Y8N10.hvtTEnQ77MZyw37wv-A06Rz4XgImhdxxllCZTQLiRG0
Refresh Token: CeVd5hfnWppHP8xQScCFZjuqd5FROXG7SqIghUYxxVU.uRSryI0bCDmTx6WWBuhmYr0fXrziidNhlTAv6q8zGVM
Expires in: 2016-06-05 23:28:17.617825487 +0200 CEST
```

The second time I visit I get an error and that's ok.

However the IdP gets called anyway and this is probably bad.

**Comment by arekkas** [comment]
if an error occurs, the idp url should contain a uri query param called `error`. the error should be taken by the idp and displayed :)

this happens when, according to spec, hydra is not allowed to redirect back to the client callback when an error occurs.

let me know if the error param is not available and reopen this issue.

**Comment by arekkas** [comment]
However, this should be documented
